import assert from 'node:assert/strict';
import {buildSectionFinalPrompt} from '../netlify/functions/generate-interior.js';
import fs from 'node:fs';
import vm from 'node:vm';
const brand={storeConcept:'neighborhood cafe',overallMood:'calm',colors:['purple'],materials:['wood']};
const baseline=buildSectionFinalPrompt('space',brand,'','',0);
const brief=buildSectionFinalPrompt('space',brand,'','',0,'Close up of our ceramic signature display');
assert.ok(brief.finalPrompt.includes('ceramic signature display'));
assert.ok(brief.finalPrompt.includes('neighborhood cafe'));
assert.ok(brief.finalPrompt.includes('purple'));
assert.equal(buildSectionFinalPrompt('space',brand,'','',0,'').finalPrompt,baseline.finalPrompt);
console.log('PASS section-specific brief, brand context and empty-brief fallback');
const constrained={...brand,avoid:['chairs','alcohol bottles'],layoutDirection:'Keep existing kitchen position',seatingDirection:'No customer seating',mustHave:['existing refrigerator']};
const plan=buildSectionFinalPrompt('space',constrained,'','',0);
assert.match(plan.finalPrompt,/Keep existing kitchen position/);
assert.match(plan.finalPrompt,/No customer seating/);
assert.match(plan.finalPrompt,/existing refrigerator/);
assert.match(plan.negativePrompt,/chairs/);
assert.match(buildSectionFinalPrompt('space',constrained,'','change wall color',0).negativePrompt,/alcohol bottles/);
const source=fs.readFileSync(new URL('../netlify/functions/generate-interior.js',import.meta.url),'utf8').split(/^export default/m)[0].replace(/^import .*;\r?\n/gm,'').replace(/^export /gm,'');
let sent;
const context={AbortController,setTimeout,clearTimeout,Buffer,process:{env:{}},fetch:async(_url,init)=>{sent=JSON.parse(init.body);return {ok:true,json:async()=>({polling_url:'https://api.bfl.ai/result/test'})};}};
vm.createContext(context);vm.runInContext(source+'\nglobalThis.submit=submitFluxTxt2Img;',context);
await context.submit(plan.finalPrompt,'test-only',plan.negativePrompt);
assert.match(sent.prompt,/Exclude from the image:.*chairs/);
assert.match(sent.prompt,/No customer seating/);
console.log('PASS actual image provider request includes exclusions and confirmed space plan');
vm.runInContext('globalThis.structure=buildStructurePrompt;globalThis.transform=getTransformLevel;',context);
const notes='의자와 테이블 유지, 바닥 교체 금지. 창문 위치 유지.';
const preserved=context.structure('interior',{changeScope:'partial',budgetMemo:notes},0);
assert.ok(preserved.prompt.includes(notes));assert.ok(!preserved.prompt.includes('Furniture replacement included'));assert.ok(!preserved.prompt.includes('Flooring replacement included'));assert.match(preserved.prompt,/override renovation scope/);
assert.equal(context.transform('full','','공사 금지').tier,1);
assert.equal(context.transform('full','','공사 예산은 상관없음').tier,4);
assert.equal(context.transform('sign','','').tier,1);
assert.ok(!context.structure('interior',{changeScope:'sign'},1).prompt.includes('toward the seating'));
console.log('PASS preservation notes remain intact, override defaults, and do not turn furniture mentions into replacement orders');
