import assert from 'node:assert/strict';
import {buildSectionFinalPrompt} from '../netlify/functions/generate-interior.js';
import fs from 'node:fs';
import vm from 'node:vm';
const brand={storeConcept:'neighborhood cafe',overallMood:'calm',colors:['purple'],materials:['wood']};
const baseline=buildSectionFinalPrompt('space',brand,'','',0);
const brief=buildSectionFinalPrompt('space',brand,'','',0,'Close up of our ceramic signature display');
assert.ok(brief.finalPrompt.includes('ceramic signature display'));
assert.ok(brief.finalPrompt.includes('neighborhood cafe'));
assert.ok(brief.finalPrompt.includes('purple'));
assert.equal(buildSectionFinalPrompt('space',brand,'','',0,'').finalPrompt,baseline.finalPrompt);
console.log('PASS section-specific brief, brand context and empty-brief fallback');
const constrained={...brand,avoid:['chairs','alcohol bottles'],layoutDirection:'Keep existing kitchen position',seatingDirection:'No customer seating',mustHave:['existing refrigerator']};
const plan=buildSectionFinalPrompt('space',constrained,'','',0);
assert.match(plan.finalPrompt,/Keep existing kitchen position/);
assert.match(plan.finalPrompt,/No customer seating/);
assert.match(plan.finalPrompt,/existing refrigerator/);
assert.match(plan.negativePrompt,/chairs/);
assert.match(buildSectionFinalPrompt('space',constrained,'','change wall color',0).negativePrompt,/alcohol bottles/);
const source=fs.readFileSync(new URL('../netlify/functions/generate-interior.js',import.meta.url),'utf8').split(/^export default/m)[0].replace(/^import .*;\r?\n/gm,'').replace(/^export /gm,'');
let sent;
const context={AbortController,setTimeout,clearTimeout,Buffer,process:{env:{}},fetch:async(_url,init)=>{sent=JSON.parse(init.body);return {ok:true,json:async()=>({polling_url:'https://api.bfl.ai/result/test'})};}};
vm.createContext(context);vm.runInContext(source+'\nglobalThis.submit=submitFluxTxt2Img;',context);
await context.submit(plan.finalPrompt,'test-only',plan.negativePrompt);
assert.match(sent.prompt,/Exclude from the image:.*chairs/);
assert.match(sent.prompt,/No customer seating/);
console.log('PASS actual image provider request includes exclusions and confirmed space plan');
